import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Vercel Postgress by 0xNunana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <p className='bg-blue-500'>COMMUNITY DATABASE</p>
        <p>username</p>
        <p>image</p>
        <p>email</p>
        <p>password</p>
      </main>
    </>
  )
}
